apiVersion: apps/v1

kind: Deployment

metadata:
    name: api-server

spec:
    replicas: 1
  
    selector:
        matchLabels:
            app: api-server
            
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1

    template:
        metadata:
            labels:
                app: api-server
                tier: frontend
                persistance: disposable
                project: news

        spec:
          containers:
          - name:  api-server
            image: moritzgoeckel/news-service:api-server 
            ports:
            - containerPort: 80
            imagePullPolicy: Always
            env:
            - name: cache-redis-url
              value: cache-redis.default.svc.cluster.local
            - name: mongo-url
              value: mongodb.default.svc.cluster.local
            - name: mongo-user
              value: root
            - name: mongo-pw
              value: thepw
            - name: elastic-url
              value: elastic.default.svc.cluster.local
---

apiVersion: v1

kind: Service

metadata:
    name: api-server 
    namespace: default
    labels:
        project: news
        tier: frontend
        app: api-server

spec:
    type: LoadBalancer
    ports:
      - port: 80
        nodePort: 30003
        protocol: TCP
    selector:
        app: api-server

# Internal URL
# api-server.default.svc.cluster.local
