apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: downloader
spec:
  startingDeadlineSeconds: 3000
  schedule: "*/2 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: downloader
            image: moritzgoeckel/news-service:downloader
          restartPolicy: OnFailure
