apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: downloader
spec:
  startingDeadlineSeconds: 3000
  schedule: "*/2 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: downloader
            image: moritzgoeckel/news-service:downloader
            env:
            - name: agt-redis-url
              value: agt-redis.default.svc.cluster.local
            - name: pq-redis-url
              value: pq-redis.default.svc.cluster.local
          restartPolicy: OnFailure
