apiVersion: apps/v1

kind: Deployment

metadata:
    name: elastic

spec:
    replicas: 1

    selector:
        matchLabels:
            app: elastic

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1

    template:
        metadata:
            labels:
                app: elastic
                tier: backend
                persistance: non-disposable
                project: news

        spec:
          containers:
          - name: elastic
            image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
            env:
            - name: cluster.name
              value: elastic-cluster
            - name: bootstrap.memory_lock
              value: true            
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            ports:
            - containerPort: 9200
            volumeMounts:
            - mountPath: /usr/share/elasticsearch/data/
              name: elastic-volume
              readOnly: false

          volumes:
          - name: elastic-volume
            hostPath:
                path: /home/docker/data/elastic-volume/
                type: DirectoryOrCreate
---

apiVersion: v1

kind: Service

metadata:
    name: elastic
    namespace: default
    labels:
        project: news
        tier: backend
        app: elastic

spec:
    type: ClusterIP
    ports:
      - port: 9200 
        targetPort: 9200
        protocol: TCP
    selector:
        app: elastic

# elastic.default.svc.cluster.local
