apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: headline-analyzer
spec:
  startingDeadlineSeconds: 3000
  schedule: "*/40 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: headline-analyzer
            image: joapfel/headlineanalyzer:0.01
            imagePullPolicy: Always
            env:
            - name: mongo-url
              value: mongodb.default.svc.cluster.local
            - name: mongo-user
              value: root
            - name: mongo-pw
              value: thepw
          restartPolicy: OnFailure