apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: link-downloader
spec:
  startingDeadlineSeconds: 3000
  schedule: "*/20 * * * *" #*/30 * * * *
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: downloader
            image: moritzgoeckel/news-service:link-downloader
            imagePullPolicy: Always
            env:
            - name: agt-link-redis-url
              value: agt-link-redis.default.svc.cluster.local
            - name: lq-redis-url
              value: lq-redis.default.svc.cluster.local
          restartPolicy: OnFailure
