apiVersion: apps/v1

kind: Deployment

metadata:
    name: mongodb

spec:
    replicas: 1

    selector:
        matchLabels:
            app: mongodb

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1

    template:
        metadata:
            labels:
                app: mongodb
                tier: backend
                persistance: non-disposable
                project: news

        spec:
          containers:
          - name: mongodb
            image: mongo
            env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: thepw            
            ports:
            - containerPort: 27017
            volumeMounts:
            - mountPath: /data/db/
              name: mongodb-volume
              readOnly: false

          volumes:
          - name: mongodb-volume
            hostPath:
                path: /home/docker/data/mongodb-volume/
                type: DirectoryOrCreate
---

apiVersion: v1

kind: Service

metadata:
    name: mongodb
    namespace: default
    labels:
        project: news
        tier: backend
        app: mongodb

spec:
    type: ClusterIP
    ports:
      - port: 27017 
        targetPort: 27017
        protocol: TCP
    selector:
        app: mongodb

# mongodb.default.svc.cluster.local
