apiVersion: apps/v1

kind: Deployment

metadata:
    name: processor

spec:
    replicas: 1

    selector:
        matchLabels:
            app: processor

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1

    template:
        metadata:
            labels:
                app: processor
                tier: backend
                persistance: disposable
                project: news

        spec:
          containers:
          - name: processor
            image: moritzgoeckel/news-service:processor
            env:
            - name: pq-redis-url
              value: pq-redis.default.svc.cluster.local
            - name: mongo-url
              value: mongodb.default.svc.cluster.local
            - name: mongo-user
              value: root
            - name: mongo-pw
              value: thepw
            - name: elastic-url
              value: elastic.default.svc.cluster.local
