apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wordcloud-generator
spec:
  startingDeadlineSeconds: 3000
  schedule: "18 * * * *" #*/30 * * * *
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: downloader
            image: moritzgoeckel/news-service:wordcloud-generator
            imagePullPolicy: Always
            env:
            - name: mongo-url
              value: mongodb.default.svc.cluster.local
            - name: mongo-user
              value: root
            - name: mongo-pw
              value: thepw
          restartPolicy: OnFailure
