# kubectl create -f frontend-depl.yml

apiVersion: apps/v1

kind: Deployment

metadata:
    name: static-frontend-server

spec:
    replicas: 1
  
    selector:
        matchLabels:
            app: static-frontend-server
            
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1

    template:
        metadata:
            labels:
                app: static-frontend-server
                tier: frontend
                persistance: disposable
                project: news

        spec:
          containers:
          - name: frontend-httpd
            # Could use nginx
            image: httpd
            ports:
            - containerPort: 80
            volumeMounts:
            - mountPath: /usr/local/apache2/htdocs/
              name: static-content-volume
              readOnly: true

          volumes:
            - name: static-content-volume
              hostPath:
                path: /home/docker/data/static-content/
                # Directory needs to already exist
                type: Directory
