apiVersion: apps/v1

kind: Deployment

metadata:
    name: processing-queue

spec:
    replicas: 1

    selector:
        matchLabels:
            app: processing-queue

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1

    template:
        metadata:
            labels:
                app: processing-queue
                tier: backend
                persistance: disposable
                project: news

        spec:
          containers:
          - name: processing-queue 
            image: spotify/kafka
            ports:
            - containerPort: 9094
---
apiVersion: v1

kind: Service

metadata:
    name: processing-queue
    namespace: default
    labels:
        project: news
        tier: backend
        app: processing-queue

spec:
    type: ClusterIP
    ports:
      - port: 9094
        targetPort: 9094
        protocol: TCP
    selector:
        app: processing-queue

# processing-queue.default.svc.cluster.local
